### ISSUE TITLE
Замечания по lw4 (shop)

### ISSUE THREAD

**Issue by lulldev** [Toroshhin/lw4-shop#1]
```html
      <a href="index.html"><input type="button" value="Бытовая техника"></a>
```

лучше выпилить input

**Comment by lulldev** [comment]
`produce` - не по англицки

**Comment by lulldev** [comment]
перепишите id стили на классы

**Comment by lulldev** [comment]
```css
header img {
  position: absolute;
  height: 30px;
  border-radius: 0px 10px 10px 0px;
  background: rgb(176, 160, 252);
  padding: 5px;
  padding-right: 10px;
}
```
 
используйте классы для стилизации логотипа
